# Entrances that cannot be used to access a must_exit entrance - symmetrical to allow reverse lookups
Must_Exit_Invalid_Connections = defaultdict(set, {
    'Dark Death Mountain Ledge (East)': {'Dark Death Mountain Ledge (West)', 'Mimic Cave'},
    'Dark Death Mountain Ledge (West)': {'Dark Death Mountain Ledge (East)', 'Mimic Cave'},
    'Mimic Cave': {'Dark Death Mountain Ledge (West)', 'Dark Death Mountain Ledge (East)'},
    'Bumper Cave (Top)': {'Death Mountain Return Cave (West)'},
    'Death Mountain Return Cave (West)': {'Bumper Cave (Top)'},
    'Skull Woods Second Section Door (West)': {'Skull Woods Final Section'},
    'Skull Woods Final Section': {'Skull Woods Second Section Door (West)'},
})
Inverted_Must_Exit_Invalid_Connections = defaultdict(set, {
    'Bumper Cave (Top)': {'Death Mountain Return Cave (West)'},
    'Death Mountain Return Cave (West)': {'Bumper Cave (Top)'},
    'Desert Palace Entrance (North)': {'Desert Palace Entrance (West)'},
    'Desert Palace Entrance (West)': {'Desert Palace Entrance (North)'},
    'Inverted Ganons Tower': {'Hyrule Castle Entrance (West)', 'Hyrule Castle Entrance (East)'},
    'Hyrule Castle Entrance (West)': {'Hyrule Castle Entrance (East)', 'Inverted Ganons Tower'},
    'Hyrule Castle Entrance (East)': {'Hyrule Castle Entrance (West)', 'Inverted Ganons Tower'},
})

# these are connections that cannot be shuffled and always exist. They link together separate parts of the world we need to divide into regions
mandatory_connections = [('Links House S&Q', 'Links House'),
                         ('Sanctuary S&Q', 'Sanctuary'),
                         ('Old Man S&Q', 'Old Man House'),
                         ('Lake Hylia Central Island Pier', 'Lake Hylia Central Island'),
                         ('Lake Hylia Central Island Teleporter', 'Dark Lake Hylia Central Island'),
                         ('Zoras River', 'Zoras River'),
                         ('Kings Grave Outer Rocks', 'Kings Grave Area'),
                         ('Kings Grave Inner Rocks', 'Light World'),
                         ('Kings Grave Mirror Spot', 'Kings Grave Area'),
                         ('Kakariko Well (top to bottom)', 'Kakariko Well (bottom)'),
                         ('Master Sword Meadow', 'Master Sword Meadow'),
                         ('Hobo Bridge', 'Hobo Bridge'),
                         ('Desert Palace East Wing', 'Desert Palace East'),
                         ('Bat Cave Drop Ledge', 'Bat Cave Drop Ledge'),
                         ('Bat Cave Door', 'Bat Cave (left)'),
                         ('Lost Woods Hideout (top to bottom)', 'Lost Woods Hideout (bottom)'),
                         ('Lumberjack Tree (top to bottom)', 'Lumberjack Tree (bottom)'),
                         ('Desert Palace Stairs', 'Desert Palace Stairs'),
                         ('Desert Palace Stairs Drop', 'Light World'),
                         ('Desert Palace Entrance (North) Rocks', 'Desert Palace Entrance (North) Spot'),
                         ('Desert Ledge Return Rocks', 'Desert Ledge'),
                         ('Hyrule Castle Ledge Courtyard Drop', 'Hyrule Castle Courtyard'),
                         ('Hyrule Castle Main Gate', 'Hyrule Castle Courtyard'),
                         ('Throne Room', 'Sewers (Dark)'),
                         ('Sewers Door', 'Sewers'),
                         ('Sanctuary Push Door', 'Sanctuary'),
                         ('Sewer Drop', 'Sewers'),
                         ('Sewers Back Door', 'Sewers (Dark)'),
                         ('Agahnim 1', 'Agahnim 1'),
                         ('Flute Spot 1', 'Death Mountain'),
                         ('Death Mountain Entrance Rock', 'Death Mountain Entrance'),
                         ('Death Mountain Entrance Drop', 'Light World'),
                         ('Spectacle Rock Cave Drop', 'Spectacle Rock Cave (Bottom)'),
                         ('Spectacle Rock Cave Peak Drop', 'Spectacle Rock Cave (Bottom)'),
                         ('Death Mountain Return Ledge Drop', 'Light World'),
                         ('Old Man House Front to Back', 'Old Man House Back'),
                         ('Old Man House Back to Front', 'Old Man House'),
                         ('Broken Bridge (West)', 'East Death Mountain (Bottom)'),
                         ('Broken Bridge (East)', 'Death Mountain'),
                         ('East Death Mountain Drop', 'East Death Mountain (Bottom)'),
                         ('Spiral Cave Ledge Access', 'Spiral Cave Ledge'),
                         ('Spiral Cave Ledge Drop', 'East Death Mountain (Bottom)'),
                         ('Spiral Cave (top to bottom)', 'Spiral Cave (Bottom)'),
                         ('East Death Mountain (Top)', 'East Death Mountain (Top)'),
                         ('Death Mountain (Top)', 'Death Mountain (Top)'),
                         ('Death Mountain Drop', 'Death Mountain'),
                         ('Spectacle Rock Drop', 'Death Mountain (Top)'),
                         ('Tower of Hera Small Key Door', 'Tower of Hera (Basement)'),
                         ('Tower of Hera Big Key Door', 'Tower of Hera (Top)'),

                         ('Top of Pyramid', 'East Dark World'),
                         ('Dark Lake Hylia Drop (East)', 'Dark Lake Hylia'),
                         ('Dark Lake Hylia Drop (South)', 'Dark Lake Hylia'),
                         ('Dark Lake Hylia Teleporter', 'Dark Lake Hylia'),
                         ('Dark Lake Hylia Ledge', 'Dark Lake Hylia Ledge'),
                         ('Dark Lake Hylia Ledge Drop', 'Dark Lake Hylia'),
                         ('East Dark World Pier', 'East Dark World'),
                         ('Lake Hylia Island Mirror Spot', 'Lake Hylia Island'),
                         ('Lake Hylia Central Island Mirror Spot', 'Lake Hylia Central Island'),
                         ('Hyrule Castle Ledge Mirror Spot', 'Hyrule Castle Ledge'),
                         ('South Dark World Bridge', 'South Dark World'),
                         ('East Dark World Bridge', 'East Dark World'),
                         ('Maze Race Mirror Spot', 'Maze Race Ledge'),
                         ('Village of Outcasts Heavy Rock', 'West Dark World'),
                         ('Village of Outcasts Drop', 'South Dark World'),
                         ('Village of Outcasts Eastern Rocks', 'Hammer Peg Area'),
                         ('Village of Outcasts Pegs', 'Dark Grassy Lawn'),
                         ('Peg Area Rocks', 'West Dark World'),
                         ('Grassy Lawn Pegs', 'West Dark World'),
                         ('Bat Cave Drop Ledge Mirror Spot', 'Bat Cave Drop Ledge'),
                         ('East Dark World River Pier', 'East Dark World'),
                         ('West Dark World Gap', 'West Dark World'),
                         ('East Dark World Broken Bridge Pass', 'East Dark World'),
                         ('Catfish Exit Rock', 'Northeast Dark World'),
                         ('Catfish Entrance Rock', 'Catfish'),
                         ('Northeast Dark World Broken Bridge Pass', 'Northeast Dark World'),
                         ('Bumper Cave Entrance Rock', 'Bumper Cave Entrance'),
                         ('Bumper Cave Entrance Drop', 'West Dark World'),
                         ('Bumper Cave Entrance Mirror Spot', 'Death Mountain Entrance'),
                         ('Bumper Cave Ledge Drop', 'West Dark World'),
                         ('Bumper Cave Ledge Mirror Spot', 'Death Mountain Return Ledge'),
                         ('Skull Woods Forest', 'Skull Woods Forest'),
                         ('Desert Ledge Mirror Spot', 'Desert Ledge'),
                         ('Desert Ledge (Northeast) Mirror Spot', 'Desert Ledge (Northeast)'),
                         ('Desert Palace Entrance (North) Mirror Spot', 'Desert Palace Entrance (North) Spot'),
                         ('Dark Desert Teleporter', 'Dark Desert'),
                         ('Desert Palace Stairs Mirror Spot', 'Desert Palace Stairs'),
                         ('East Hyrule Teleporter', 'East Dark World'),
                         ('South Hyrule Teleporter', 'South Dark World'),
                         ('Kakariko Teleporter', 'West Dark World'),
                         ('Death Mountain Teleporter', 'Dark Death Mountain (West Bottom)'),
                         ('Paradox Cave Push Block Reverse', 'Paradox Cave Chest Area'),
                         ('Paradox Cave Push Block', 'Paradox Cave Front'),
                         ('Paradox Cave Bomb Jump', 'Paradox Cave'),
                         ('Paradox Cave Drop', 'Paradox Cave Chest Area'),
                         ('Light World Death Mountain Shop', 'Light World Death Mountain Shop'),
                         ('Fairy Ascension Rocks', 'Fairy Ascension Plateau'),
                         ('Fairy Ascension Mirror Spot', 'Fairy Ascension Plateau'),
                         ('Fairy Ascension Drop', 'East Death Mountain (Bottom)'),
                         ('Fairy Ascension Ledge Drop', 'Fairy Ascension Plateau'),
                         ('Fairy Ascension Ledge', 'Fairy Ascension Ledge'),
                         ('Fairy Ascension Cave Climb', 'Fairy Ascension Cave (Top)'),
                         ('Fairy Ascension Cave Pots', 'Fairy Ascension Cave (Bottom)'),
                         ('Fairy Ascension Cave Drop', 'Fairy Ascension Cave (Drop)'),
                         ('Spectacle Rock Mirror Spot', 'Spectacle Rock'),
                         ('Dark Death Mountain Drop (East)', 'Dark Death Mountain (East Bottom)'),
                         ('Dark Death Mountain Drop (West)', 'Dark Death Mountain (West Bottom)'),
                         ('East Death Mountain (Top) Mirror Spot', 'East Death Mountain (Top)'),
                         ('Turtle Rock Teleporter', 'Turtle Rock (Top)'),
                         ('Turtle Rock Drop', 'Dark Death Mountain (Top)'),
                         ('Floating Island Drop', 'Dark Death Mountain (Top)'),
                         ('Floating Island Mirror Spot', 'Death Mountain Floating Island (Light World)'),
                         ('East Death Mountain Teleporter', 'Dark Death Mountain (East Bottom)'),
                         ('Isolated Ledge Mirror Spot', 'Fairy Ascension Ledge'),
                         ('Spiral Cave Mirror Spot', 'Spiral Cave Ledge'),
                         ('Mimic Cave Mirror Spot', 'Mimic Cave Ledge'),
                         ('Cave 45 Mirror Spot', 'Cave 45 Ledge'),
                         ('Bombos Tablet Mirror Spot', 'Bombos Tablet Ledge'),
                         ('Graveyard Ledge Mirror Spot', 'Graveyard Ledge'),
                         ('Superbunny Cave Climb', 'Superbunny Cave (Top)'),

                         ('Swamp Palace Moat', 'Swamp Palace (First Room)'),
                         ('Swamp Palace Small Key Door', 'Swamp Palace (Starting Area)'),
                         ('Swamp Palace (Center)', 'Swamp Palace (Center)'),
                         ('Swamp Palace (North)', 'Swamp Palace (North)'),
                         ('Thieves Town Big Key Door', 'Thieves Town (Deep)'),
                         ('Skull Woods Torch Room', 'Skull Woods Final Section (Mothula)'),
                         ('Skull Woods First Section Bomb Jump', 'Skull Woods First Section (Top)'),
                         # represents bomb jumping to big chest
                         ('Skull Woods First Section South Door', 'Skull Woods First Section (Right)'),
                         ('Skull Woods First Section West Door', 'Skull Woods First Section (Left)'),
                         ('Skull Woods First Section (Right) North Door', 'Skull Woods First Section'),
                         ('Skull Woods First Section (Left) Door to Right', 'Skull Woods First Section (Right)'),
                         ('Skull Woods First Section (Left) Door to Exit', 'Skull Woods First Section'),
                         ('Skull Woods First Section (Top) One-Way Path', 'Skull Woods First Section'),
                         ('Skull Woods Second Section (Drop)', 'Skull Woods Second Section'),
                         ('Blind Fight', 'Blind Fight'),
                         ('Desert Palace Pots (Outer)', 'Desert Palace Main (Inner)'),
                         ('Desert Palace Pots (Inner)', 'Desert Palace Main (Outer)'),
                         ('Ice Palace Entrance Room', 'Ice Palace (Main)'),
                         ('Ice Palace (East)', 'Ice Palace (East)'),
                         ('Ice Palace (East Top)', 'Ice Palace (East Top)'),
                         ('Ice Palace (Kholdstare)', 'Ice Palace (Kholdstare)'),
                         ('Misery Mire Entrance Gap', 'Misery Mire (Main)'),
                         ('Misery Mire (West)', 'Misery Mire (West)'),
                         ('Misery Mire Big Key Door', 'Misery Mire (Final Area)'),
                         ('Misery Mire (Vitreous)', 'Misery Mire (Vitreous)'),
                         ('Turtle Rock Entrance Gap', 'Turtle Rock (First Section)'),
                         ('Turtle Rock Entrance Gap Reverse', 'Turtle Rock (Entrance)'),
                         ('Turtle Rock Pokey Room', 'Turtle Rock (Chain Chomp Room)'),
                         ('Turtle Rock (Chain Chomp Room) (North)', 'Turtle Rock (Second Section)'),
                         ('Turtle Rock (Chain Chomp Room) (South)', 'Turtle Rock (First Section)'),
                         ('Turtle Rock Chain Chomp Staircase', 'Turtle Rock (Chain Chomp Room)'),
                         ('Turtle Rock (Big Chest) (North)', 'Turtle Rock (Second Section)'),
                         ('Turtle Rock Big Key Door', 'Turtle Rock (Crystaroller Room)'),
                         ('Turtle Rock Big Key Door Reverse', 'Turtle Rock (Second Section)'),
                         ('Turtle Rock Dark Room Staircase', 'Turtle Rock (Dark Room)'),
                         ('Turtle Rock (Dark Room) (North)', 'Turtle Rock (Crystaroller Room)'),
                         ('Turtle Rock (Dark Room) (South)', 'Turtle Rock (Eye Bridge)'),
                         ('Turtle Rock Dark Room (South)', 'Turtle Rock (Dark Room)'),
                         ('Turtle Rock (Trinexx)', 'Turtle Rock (Trinexx)'),
                         ('Palace of Darkness Bridge Room', 'Palace of Darkness (Center)'),
                         ('Palace of Darkness Bonk Wall', 'Palace of Darkness (Bonk Section)'),
                         ('Palace of Darkness Big Key Chest Staircase', 'Palace of Darkness (Big Key Chest)'),
                         ('Palace of Darkness (North)', 'Palace of Darkness (North)'),
                         ('Palace of Darkness Big Key Door', 'Palace of Darkness (Final Section)'),
                         ('Palace of Darkness Hammer Peg Drop', 'Palace of Darkness (Center)'),
                         ('Palace of Darkness Spike Statue Room Door', 'Palace of Darkness (Harmless Hellway)'),
                         ('Palace of Darkness Maze Door', 'Palace of Darkness (Maze)'),
                         ('Ganons Tower (Tile Room)', 'Ganons Tower (Tile Room)'),
                         ('Ganons Tower (Tile Room) Key Door', 'Ganons Tower (Compass Room)'),
                         ('Ganons Tower (Bottom) (East)', 'Ganons Tower (Bottom)'),
                         ('Ganons Tower (Hookshot Room)', 'Ganons Tower (Hookshot Room)'),
                         ('Ganons Tower (Map Room)', 'Ganons Tower (Map Room)'),
                         ('Ganons Tower (Double Switch Room)', 'Ganons Tower (Firesnake Room)'),
                         ('Ganons Tower (Firesnake Room)', 'Ganons Tower (Teleport Room)'),
                         ('Ganons Tower (Bottom) (West)', 'Ganons Tower (Bottom)'),
                         ('Ganons Tower Big Key Door', 'Ganons Tower (Top)'),
                         ('Ganons Tower Torch Rooms', 'Ganons Tower (Before Moldorm)'),
                         ('Ganons Tower Moldorm Door', 'Ganons Tower (Moldorm)'),
                         ('Ganons Tower Moldorm Gap', 'Agahnim 2'),
                         ('Ganon Drop', 'Bottom of Pyramid'),
                         ('Pyramid Drop', 'East Dark World')
                         ]

inverted_mandatory_connections = [('Links House S&Q', 'Inverted Links House'),
                                  ('Dark Sanctuary S&Q', 'Inverted Dark Sanctuary'),
                                  ('Old Man S&Q', 'Old Man House'),
                                  ('Castle Ledge S&Q', 'Hyrule Castle Ledge'),
                                  ('Lake Hylia Central Island Pier', 'Lake Hylia Central Island'),
                                  ('Lake Hylia Island Pier', 'Lake Hylia Island'),
                                  ('Lake Hylia Warp', 'Northeast Light World'),
                                  ('Northeast Light World Warp', 'Light World'),
                                  ('Zoras River', 'Zoras River'),
                                  ('Waterfall of Wishing Cave', 'Waterfall of Wishing Cave'),
                                  ('Northeast Light World Return', 'Northeast Light World'),
                                  ('Kings Grave Outer Rocks', 'Kings Grave Area'),
                                  ('Kings Grave Inner Rocks', 'Light World'),
                                  ('Kakariko Well (top to bottom)', 'Kakariko Well (bottom)'),
                                  ('Master Sword Meadow', 'Master Sword Meadow'),
                                  ('Hobo Bridge', 'Hobo Bridge'),
                                  ('Desert Palace East Wing', 'Desert Palace East'),
                                  ('Bat Cave Drop Ledge', 'Bat Cave Drop Ledge'),
                                  ('Bat Cave Door', 'Bat Cave (left)'),
                                  ('Lost Woods Hideout (top to bottom)', 'Lost Woods Hideout (bottom)'),
                                  ('Lumberjack Tree (top to bottom)', 'Lumberjack Tree (bottom)'),
                                  ('Desert Palace Stairs', 'Desert Palace Stairs'),
                                  ('Desert Palace Stairs Drop', 'Light World'),
                                  ('Desert Palace Entrance (North) Rocks', 'Desert Palace Entrance (North) Spot'),
                                  ('Desert Ledge Return Rocks', 'Desert Ledge'),
                                  ('Throne Room', 'Sewers (Dark)'), ('Sewers Door', 'Sewers'),
                                  ('Sanctuary Push Door', 'Sanctuary'),
                                  ('Sewer Drop', 'Sewers'),
                                  ('Sewers Back Door', 'Sewers (Dark)'),
                                  ('Agahnim 1', 'Agahnim 1'),
                                  ('Death Mountain Entrance Rock', 'Death Mountain Entrance'),
                                  ('Death Mountain Entrance Drop', 'Light World'),
                                  ('Spectacle Rock Cave Drop', 'Spectacle Rock Cave (Bottom)'),
                                  ('Spectacle Rock Cave Peak Drop', 'Spectacle Rock Cave (Bottom)'),
                                  ('Death Mountain Return Ledge Drop', 'Light World'),
                                  ('Old Man House Front to Back', 'Old Man House Back'),
                                  ('Old Man House Back to Front', 'Old Man House'),
                                  ('Broken Bridge (West)', 'East Death Mountain (Bottom)'),
                                  ('Broken Bridge (East)', 'Death Mountain'),
                                  ('East Death Mountain Drop', 'East Death Mountain (Bottom)'),
                                  ('Spiral Cave Ledge Access', 'Spiral Cave Ledge'),
                                  ('Spiral Cave Ledge Drop', 'East Death Mountain (Bottom)'),
                                  ('Spiral Cave (top to bottom)', 'Spiral Cave (Bottom)'),
                                  ('East Death Mountain (Top)', 'East Death Mountain (Top)'),
                                  ('Death Mountain (Top)', 'Death Mountain (Top)'),
                                  ('Death Mountain Drop', 'Death Mountain'),
                                  ('Tower of Hera Small Key Door', 'Tower of Hera (Basement)'),
                                  ('Tower of Hera Big Key Door', 'Tower of Hera (Top)'),
                                  ('Dark Lake Hylia Drop (East)', 'Dark Lake Hylia'),
                                  ('Dark Lake Hylia Drop (South)', 'Dark Lake Hylia'),
                                  ('Dark Lake Hylia Teleporter', 'Dark Lake Hylia'),
                                  ('Dark Lake Hylia Ledge Pier', 'Dark Lake Hylia Ledge'),
                                  ('Dark Lake Hylia Ledge Drop', 'Dark Lake Hylia'),
                                  ('Ice Palace Missing Wall', 'Dark Lake Hylia Central Island'),
                                  ('Dark Lake Hylia Shallows', 'Dark Lake Hylia'),
                                  ('East Dark World Pier', 'East Dark World'),
                                  ('South Dark World Bridge', 'South Dark World'),
                                  ('East Dark World Bridge', 'East Dark World'),
                                  ('Village of Outcasts Heavy Rock', 'West Dark World'),
                                  ('Village of Outcasts Drop', 'South Dark World'),
                                  ('Village of Outcasts Eastern Rocks', 'Hammer Peg Area'),
                                  ('Village of Outcasts Pegs', 'Dark Grassy Lawn'),
                                  ('Peg Area Rocks', 'West Dark World'),
                                  ('Grassy Lawn Pegs', 'West Dark World'),
                                  ('East Dark World River Pier', 'Northeast Dark World'),
                                  ('West Dark World Gap', 'West Dark World'),
                                  ('East Dark World Broken Bridge Pass', 'East Dark World'),
                                  ('Northeast Dark World Broken Bridge Pass', 'Northeast Dark World'),
                                  ('Catfish Exit Rock', 'Northeast Dark World'),
                                  ('Catfish Entrance Rock', 'Catfish'),
                                  ('Bumper Cave Entrance Rock', 'Bumper Cave Entrance'),
                                  ('Bumper Cave Entrance Drop', 'West Dark World'),
                                  ('Bumper Cave Ledge Drop', 'West Dark World'),
                                  ('Skull Woods Forest', 'Skull Woods Forest'),
                                  ('Paradox Cave Push Block Reverse', 'Paradox Cave Chest Area'),
                                  ('Paradox Cave Push Block', 'Paradox Cave Front'),
                                  ('Paradox Cave Bomb Jump', 'Paradox Cave'),
                                  ('Paradox Cave Drop', 'Paradox Cave Chest Area'),
                                  ('Light World Death Mountain Shop', 'Light World Death Mountain Shop'),
                                  ('Fairy Ascension Rocks', 'Fairy Ascension Plateau'),
                                  ('Fairy Ascension Drop', 'East Death Mountain (Bottom)'),
                                  ('Fairy Ascension Ledge Drop', 'Fairy Ascension Plateau'),
                                  ('Fairy Ascension Ledge Access', 'Fairy Ascension Ledge'),
                                  ('Fairy Ascension Cave Climb', 'Fairy Ascension Cave (Top)'),
                                  ('Fairy Ascension Cave Pots', 'Fairy Ascension Cave (Bottom)'),
                                  ('Fairy Ascension Cave Drop', 'Fairy Ascension Cave (Drop)'),
                                  ('Dark Death Mountain Drop (East)', 'Dark Death Mountain (East Bottom)'),
                                  ('Superbunny Cave Climb', 'Superbunny Cave (Top)'),
                                  ('Swamp Palace Moat', 'Swamp Palace (First Room)'),
                                  ('Swamp Palace Small Key Door', 'Swamp Palace (Starting Area)'),
                                  ('Swamp Palace (Center)', 'Swamp Palace (Center)'),
                                  ('Swamp Palace (North)', 'Swamp Palace (North)'),
                                  ('Thieves Town Big Key Door', 'Thieves Town (Deep)'),
                                  ('Skull Woods Torch Room', 'Skull Woods Final Section (Mothula)'),
                                  ('Skull Woods First Section Bomb Jump', 'Skull Woods First Section (Top)'),
                                  ('Skull Woods First Section South Door', 'Skull Woods First Section (Right)'),
                                  ('Skull Woods First Section West Door', 'Skull Woods First Section (Left)'),
                                  ('Skull Woods First Section (Right) North Door', 'Skull Woods First Section'),
                                  ('Skull Woods First Section (Left) Door to Right',
                                   'Skull Woods First Section (Right)'),
                                  ('Skull Woods First Section (Left) Door to Exit', 'Skull Woods First Section'),
                                  ('Skull Woods First Section (Top) One-Way Path', 'Skull Woods First Section'),
                                  ('Skull Woods Second Section (Drop)', 'Skull Woods Second Section'),
                                  ('Blind Fight', 'Blind Fight'),
                                  ('Desert Palace Pots (Outer)', 'Desert Palace Main (Inner)'),
                                  ('Desert Palace Pots (Inner)', 'Desert Palace Main (Outer)'),
                                  ('Ice Palace Entrance Room', 'Ice Palace (Main)'),
                                  ('Ice Palace (East)', 'Ice Palace (East)'),
                                  ('Ice Palace (East Top)', 'Ice Palace (East Top)'),
                                  ('Ice Palace (Kholdstare)', 'Ice Palace (Kholdstare)'),
                                  ('Misery Mire Entrance Gap', 'Misery Mire (Main)'),
                                  ('Misery Mire (West)', 'Misery Mire (West)'),
                                  ('Misery Mire Big Key Door', 'Misery Mire (Final Area)'),
                                  ('Misery Mire (Vitreous)', 'Misery Mire (Vitreous)'),
                                  ('Turtle Rock Entrance Gap', 'Turtle Rock (First Section)'),
                                  ('Turtle Rock Entrance Gap Reverse', 'Turtle Rock (Entrance)'),
                                  ('Turtle Rock Pokey Room', 'Turtle Rock (Chain Chomp Room)'),
                                  ('Turtle Rock (Chain Chomp Room) (North)', 'Turtle Rock (Second Section)'),
                                  ('Turtle Rock (Chain Chomp Room) (South)', 'Turtle Rock (First Section)'),
                                  ('Turtle Rock Chain Chomp Staircase', 'Turtle Rock (Chain Chomp Room)'),
                                  ('Turtle Rock (Big Chest) (North)', 'Turtle Rock (Second Section)'),
                                  ('Turtle Rock Big Key Door', 'Turtle Rock (Crystaroller Room)'),
                                  ('Turtle Rock Big Key Door Reverse', 'Turtle Rock (Second Section)'),
                                  ('Turtle Rock Dark Room Staircase', 'Turtle Rock (Dark Room)'),
                                  ('Turtle Rock (Dark Room) (North)', 'Turtle Rock (Crystaroller Room)'),
                                  ('Turtle Rock (Dark Room) (South)', 'Turtle Rock (Eye Bridge)'),
                                  ('Turtle Rock Dark Room (South)', 'Turtle Rock (Dark Room)'),
                                  ('Turtle Rock (Trinexx)', 'Turtle Rock (Trinexx)'),
                                  ('Palace of Darkness Bridge Room', 'Palace of Darkness (Center)'),
                                  ('Palace of Darkness Bonk Wall', 'Palace of Darkness (Bonk Section)'),
                                  ('Palace of Darkness Big Key Chest Staircase', 'Palace of Darkness (Big Key Chest)'),
                                  ('Palace of Darkness (North)', 'Palace of Darkness (North)'),
                                  ('Palace of Darkness Big Key Door', 'Palace of Darkness (Final Section)'),
                                  ('Palace of Darkness Hammer Peg Drop', 'Palace of Darkness (Center)'),
                                  (
                                  'Palace of Darkness Spike Statue Room Door', 'Palace of Darkness (Harmless Hellway)'),
                                  ('Palace of Darkness Maze Door', 'Palace of Darkness (Maze)'),
                                  ('Ganons Tower (Tile Room)', 'Ganons Tower (Tile Room)'),
                                  ('Ganons Tower (Tile Room) Key Door', 'Ganons Tower (Compass Room)'),
                                  ('Ganons Tower (Bottom) (East)', 'Ganons Tower (Bottom)'),
                                  ('Ganons Tower (Hookshot Room)', 'Ganons Tower (Hookshot Room)'),
                                  ('Ganons Tower (Map Room)', 'Ganons Tower (Map Room)'),
                                  ('Ganons Tower (Double Switch Room)', 'Ganons Tower (Firesnake Room)'),
                                  ('Ganons Tower (Firesnake Room)', 'Ganons Tower (Teleport Room)'),
                                  ('Ganons Tower (Bottom) (West)', 'Ganons Tower (Bottom)'),
                                  ('Ganons Tower Big Key Door', 'Ganons Tower (Top)'),
                                  ('Ganons Tower Torch Rooms', 'Ganons Tower (Before Moldorm)'),
                                  ('Ganons Tower Moldorm Door', 'Ganons Tower (Moldorm)'),
                                  ('Ganons Tower Moldorm Gap', 'Agahnim 2'),
                                  ('Ganon Drop', 'Bottom of Pyramid'),
                                  ('Pyramid Drop', 'East Dark World'),
                                  ('Post Aga Teleporter', 'Light World'),
                                  ('Secret Passage Inner Bushes', 'Light World'),
                                  ('Secret Passage Outer Bushes', 'Hyrule Castle Secret Entrance Area'),
                                  ('Potion Shop Inner Bushes', 'Light World'),
                                  ('Potion Shop Outer Bushes', 'Potion Shop Area'),
                                  ('Potion Shop Inner Rock', 'Northeast Light World'),
                                  ('Potion Shop Outer Rock', 'Potion Shop Area'),
                                  ('Potion Shop River Drop', 'River'),
                                  ('Graveyard Cave Inner Bushes', 'Light World'),
                                  ('Graveyard Cave Outer Bushes', 'Graveyard Cave Area'),
                                  ('Graveyard Cave Mirror Spot', 'West Dark World'),
                                  ('Light World River Drop', 'River'),
                                  ('Light World Pier', 'Light World'),
                                  ('Potion Shop Pier', 'Potion Shop Area'),
                                  ('Hyrule Castle Ledge Courtyard Drop', 'Light World'),
                                  ('Mimic Cave Ledge Access', 'Mimic Cave Ledge'),
                                  ('Mimic Cave Ledge Drop', 'East Death Mountain (Bottom)'),
                                  ('Turtle Rock Tail Drop', 'Turtle Rock (Top)'),
                                  ('Turtle Rock Drop', 'Dark Death Mountain'),
                                  ('Desert Ledge Drop', 'Light World'),
                                  ('Floating Island Drop', 'Dark Death Mountain'),
                                  ('Dark Lake Hylia Central Island Teleporter', 'Lake Hylia Central Island'),
                                  ('Dark Desert Teleporter', 'Light World'),
                                  ('East Dark World Teleporter', 'Light World'),
                                  ('South Dark World Teleporter', 'Light World'),
                                  ('West Dark World Teleporter', 'Light World'),
                                  ('Dark Death Mountain Teleporter (West)', 'Death Mountain'),
                                  ('Dark Death Mountain Teleporter (East)', 'East Death Mountain (Top)'),
                                  ('Dark Death Mountain Teleporter (East Bottom)', 'East Death Mountain (Bottom)'),
                                  ('Mire Mirror Spot', 'Dark Desert'),
                                  ('Dark Desert Drop', 'Dark Desert'),
                                  ('Desert Palace Stairs Mirror Spot', 'Dark Desert'),
                                  ('Desert Palace North Mirror Spot', 'Dark Desert'),
                                  ('Maze Race Mirror Spot', 'West Dark World'),
                                  ('Lake Hylia Central Island Mirror Spot', 'Dark Lake Hylia Central Island'),
                                  ('Hammer Peg Area Mirror Spot', 'Hammer Peg Area'),
                                  ('Bumper Cave Ledge Mirror Spot', 'Bumper Cave Ledge'),
                                  ('Bumper Cave Entrance Mirror Spot', 'Bumper Cave Entrance'),
                                  ('Death Mountain Mirror Spot', 'Dark Death Mountain'),
                                  ('East Death Mountain Mirror Spot (Top)', 'Dark Death Mountain'),
                                  ('East Death Mountain Mirror Spot (Bottom)', 'Dark Death Mountain (East Bottom)'),
                                  ('Death Mountain (Top) Mirror Spot', 'Dark Death Mountain'),
                                  ('Dark Death Mountain Ledge Mirror Spot (East)', 'Dark Death Mountain Ledge'),
                                  ('Dark Death Mountain Ledge Mirror Spot (West)', 'Dark Death Mountain Ledge'),
                                  ('Floating Island Mirror Spot', 'Death Mountain Floating Island (Dark World)'),
                                  ('Laser Bridge Mirror Spot', 'Dark Death Mountain Isolated Ledge'),
                                  ('East Dark World Mirror Spot', 'East Dark World'),
                                  ('West Dark World Mirror Spot', 'West Dark World'),
                                  ('South Dark World Mirror Spot', 'South Dark World'),
                                  ('Potion Shop Mirror Spot', 'Northeast Dark World'),
                                  ('Catfish Mirror Spot', 'Catfish'),
                                  ('Shopping Mall Mirror Spot', 'Dark Lake Hylia Ledge'),
                                  ('Skull Woods Mirror Spot', 'Skull Woods Forest (West)'),
                                  ('DDM Flute', 'The Sky'),
                                  ('DDM Landing', 'Dark Death Mountain'),
                                  ('NEDW Flute', 'The Sky'),
                                  ('NEDW Landing', 'Northeast Dark World'),
                                  ('WDW Flute', 'The Sky'),
                                  ('WDW Landing', 'West Dark World'),
                                  ('SDW Flute', 'The Sky'),
                                  ('SDW Landing', 'South Dark World'),
                                  ('EDW Flute', 'The Sky'),
                                  ('EDW Landing', 'East Dark World'),
                                  ('DLHL Flute', 'The Sky'),
                                  ('DLHL Landing', 'Dark Lake Hylia Ledge'),
                                  ('DD Flute', 'The Sky'),
                                  ('DD Landing', 'Dark Desert Ledge'),
                                  ('EDDM Flute', 'The Sky'),
                                  ('Dark Grassy Lawn Flute', 'The Sky'),
                                  ('Hammer Peg Area Flute', 'The Sky'),
                                  ('Chris Houlihan Room Exit', 'Pyramid Ledge'),
                                  ('Bush Covered Lawn Inner Bushes', 'Light World'),
                                  ('Bush Covered Lawn Outer Bushes', 'Bush Covered Lawn'),
                                  ('Bush Covered Lawn Mirror Spot', 'Dark Grassy Lawn'),
                                  ('Bomb Hut Inner Bushes', 'Light World'),
                                  ('Bomb Hut Outer Bushes', 'Bomb Hut Area'),
                                  ('Bomb Hut Mirror Spot', 'West Dark World')]
# non-shuffled entrance links
default_connections = [('Waterfall of Wishing', 'Waterfall of Wishing'),
                       ("Blinds Hideout", "Blinds Hideout"),
                       ('Dam', 'Dam'),
                       ('Lumberjack House', 'Lumberjack House'),
                       ("Hyrule Castle Secret Entrance Drop", "Hyrule Castle Secret Entrance"),
                       ("Hyrule Castle Secret Entrance Stairs", "Hyrule Castle Secret Entrance"),
                       ("Hyrule Castle Secret Entrance Exit", "Hyrule Castle Courtyard"),
                       ('Bonk Fairy (Light)', 'Bonk Fairy (Light)'),
                       ('Lake Hylia Fairy', 'Lake Hylia Healer Fairy'),
                       ('Lake Hylia Fortune Teller', 'Lake Hylia Fortune Teller'),
                       ('Light Hype Fairy', 'Swamp Healer Fairy'),
                       ('Desert Fairy', 'Desert Healer Fairy'),
                       ('Kings Grave', 'Kings Grave'),
                       ('Tavern North', 'Tavern'),
                       ('Chicken House', 'Chicken House'),
                       ('Aginahs Cave', 'Aginahs Cave'),
                       ('Sahasrahlas Hut', 'Sahasrahlas Hut'),
                       ('Cave Shop (Lake Hylia)', 'Cave Shop (Lake Hylia)'),
                       ('Capacity Upgrade', 'Capacity Upgrade'),
                       ('Kakariko Well Drop', 'Kakariko Well (top)'),
                       ('Kakariko Well Cave', 'Kakariko Well (bottom)'),
                       ('Kakariko Well Exit', 'Light World'),
                       ('Blacksmiths Hut', 'Blacksmiths Hut'),
                       ('Bat Cave Drop', 'Bat Cave (right)'),
                       ('Bat Cave Cave', 'Bat Cave (left)'),
                       ('Bat Cave Exit', 'Light World'),
                       ('Sick Kids House', 'Sick Kids House'),
                       ('Elder House (East)', 'Elder House'),
                       ('Elder House (West)', 'Elder House'),
                       ('Elder House Exit (East)', 'Light World'),
                       ('Elder House Exit (West)', 'Light World'),
                       ('North Fairy Cave Drop', 'North Fairy Cave'),
                       ('North Fairy Cave', 'North Fairy Cave'),
                       ('North Fairy Cave Exit', 'Light World'),
                       ('Lost Woods Gamble', 'Lost Woods Gamble'),
                       ('Fortune Teller (Light)', 'Fortune Teller (Light)'),
                       ('Snitch Lady (East)', 'Snitch Lady (East)'),
                       ('Snitch Lady (West)', 'Snitch Lady (West)'),
                       ('Bush Covered House', 'Bush Covered House'),
                       ('Tavern (Front)', 'Tavern (Front)'),
                       ('Light World Bomb Hut', 'Light World Bomb Hut'),
                       ('Kakariko Shop', 'Kakariko Shop'),
                       ('Lost Woods Hideout Drop', 'Lost Woods Hideout (top)'),
                       ('Lost Woods Hideout Stump', 'Lost Woods Hideout (bottom)'),
                       ('Lost Woods Hideout Exit', 'Light World'),
                       ('Lumberjack Tree Tree', 'Lumberjack Tree (top)'),
                       ('Lumberjack Tree Cave', 'Lumberjack Tree (bottom)'),
                       ('Lumberjack Tree Exit', 'Light World'),
                       ('Cave 45', 'Cave 45'),
                       ('Graveyard Cave', 'Graveyard Cave'),
                       ('Checkerboard Cave', 'Checkerboard Cave'),
                       ('Mini Moldorm Cave', 'Mini Moldorm Cave'),
                       ('Long Fairy Cave', 'Long Fairy Cave'),  # near East Light World Teleporter
                       ('Good Bee Cave', 'Good Bee Cave'),
                       ('20 Rupee Cave', '20 Rupee Cave'),
                       ('50 Rupee Cave', '50 Rupee Cave'),
                       ('Ice Rod Cave', 'Ice Rod Cave'),
                       ('Bonk Rock Cave', 'Bonk Rock Cave'),
                       ('Library', 'Library'),
                       ('Kakariko Gamble Game', 'Kakariko Gamble Game'),
                       ('Potion Shop', 'Potion Shop'),
                       ('Two Brothers House (East)', 'Two Brothers House'),
                       ('Two Brothers House (West)', 'Two Brothers House'),
                       ('Two Brothers House Exit (East)', 'Light World'),
                       ('Two Brothers House Exit (West)', 'Maze Race Ledge'),

                       ('Sanctuary', 'Sanctuary'),
                       ('Sanctuary Grave', 'Sewer Drop'),
                       ('Sanctuary Exit', 'Light World'),

                       ('Old Man Cave (West)', 'Old Man Cave'),
                       ('Old Man Cave (East)', 'Old Man Cave'),
                       ('Old Man Cave Exit (West)', 'Light World'),
                       ('Old Man Cave Exit (East)', 'Death Mountain'),
                       ('Old Man House (Bottom)', 'Old Man House'),
                       ('Old Man House Exit (Bottom)', 'Death Mountain'),
                       ('Old Man House (Top)', 'Old Man House Back'),
                       ('Old Man House Exit (Top)', 'Death Mountain'),
                       ('Death Mountain Return Cave (East)', 'Death Mountain Return Cave'),
                       ('Death Mountain Return Cave (West)', 'Death Mountain Return Cave'),
                       ('Death Mountain Return Cave Exit (West)', 'Death Mountain Return Ledge'),
                       ('Death Mountain Return Cave Exit (East)', 'Death Mountain'),
                       ('Spectacle Rock Cave Peak', 'Spectacle Rock Cave (Peak)'),
                       ('Spectacle Rock Cave (Bottom)', 'Spectacle Rock Cave (Bottom)'),
                       ('Spectacle Rock Cave', 'Spectacle Rock Cave (Top)'),
                       ('Spectacle Rock Cave Exit', 'Death Mountain'),
                       ('Spectacle Rock Cave Exit (Top)', 'Death Mountain'),
                       ('Spectacle Rock Cave Exit (Peak)', 'Death Mountain'),
                       ('Paradox Cave (Bottom)', 'Paradox Cave Front'),
                       ('Paradox Cave (Middle)', 'Paradox Cave'),
                       ('Paradox Cave (Top)', 'Paradox Cave'),
                       ('Paradox Cave Exit (Bottom)', 'East Death Mountain (Bottom)'),
                       ('Paradox Cave Exit (Middle)', 'East Death Mountain (Bottom)'),
                       ('Paradox Cave Exit (Top)', 'East Death Mountain (Top)'),
                       ('Hookshot Fairy', 'Hookshot Fairy'),
                       ('Fairy Ascension Cave (Bottom)', 'Fairy Ascension Cave (Bottom)'),
                       ('Fairy Ascension Cave (Top)', 'Fairy Ascension Cave (Top)'),
                       ('Fairy Ascension Cave Exit (Bottom)', 'Fairy Ascension Plateau'),
                       ('Fairy Ascension Cave Exit (Top)', 'Fairy Ascension Ledge'),
                       ('Spiral Cave', 'Spiral Cave (Top)'),
                       ('Spiral Cave (Bottom)', 'Spiral Cave (Bottom)'),
                       ('Spiral Cave Exit', 'East Death Mountain (Bottom)'),
                       ('Spiral Cave Exit (Top)', 'Spiral Cave Ledge'),

                       ('Pyramid Fairy', 'Pyramid Fairy'),
                       ('East Dark World Hint', 'East Dark World Hint'),
                       ('Palace of Darkness Hint', 'Palace of Darkness Hint'),
                       ('Big Bomb Shop', 'Big Bomb Shop'),
                       ('Dark Lake Hylia Shop', 'Dark Lake Hylia Shop'),
                       ('Dark Lake Hylia Fairy', 'Dark Lake Hylia Healer Fairy'),
                       ('Dark Lake Hylia Ledge Fairy', 'Dark Lake Hylia Ledge Healer Fairy'),
                       ('Dark Lake Hylia Ledge Spike Cave', 'Dark Lake Hylia Ledge Spike Cave'),
                       ('Dark Lake Hylia Ledge Hint', 'Dark Lake Hylia Ledge Hint'),
                       ('Hype Cave', 'Hype Cave'),
                       ('Bonk Fairy (Dark)', 'Bonk Fairy (Dark)'),
                       ('Brewery', 'Brewery'),
                       ('C-Shaped House', 'C-Shaped House'),
                       ('Chest Game', 'Chest Game'),
                       ('Dark World Hammer Peg Cave', 'Dark World Hammer Peg Cave'),
                       ('Bumper Cave (Bottom)', 'Bumper Cave'),
                       ('Bumper Cave (Top)', 'Bumper Cave'),
                       ('Red Shield Shop', 'Red Shield Shop'),
                       ('Dark Sanctuary Hint', 'Dark Sanctuary Hint'),
                       ('Fortune Teller (Dark)', 'Fortune Teller (Dark)'),
                       ('Dark World Shop', 'Village of Outcasts Shop'),
                       ('Dark World Lumberjack Shop', 'Dark World Lumberjack Shop'),
                       ('Dark World Potion Shop', 'Dark World Potion Shop'),
                       ('Archery Game', 'Archery Game'),
                       ('Bumper Cave Exit (Top)', 'Bumper Cave Ledge'),
                       ('Bumper Cave Exit (Bottom)', 'West Dark World'),
                       ('Mire Shed', 'Mire Shed'),
                       ('Dark Desert Hint', 'Dark Desert Hint'),
                       ('Dark Desert Fairy', 'Dark Desert Healer Fairy'),
                       ('Spike Cave', 'Spike Cave'),
                       ('Hookshot Cave', 'Hookshot Cave'),
                       ('Superbunny Cave (Top)', 'Superbunny Cave (Top)'),
                       ('Cave Shop (Dark Death Mountain)', 'Cave Shop (Dark Death Mountain)'),
                       ('Dark Death Mountain Fairy', 'Dark Death Mountain Healer Fairy'),
                       ('Superbunny Cave (Bottom)', 'Superbunny Cave (Bottom)'),
                       ('Superbunny Cave Exit (Top)', 'Dark Death Mountain (Top)'),
                       ('Superbunny Cave Exit (Bottom)', 'Dark Death Mountain (East Bottom)'),
                       ('Hookshot Cave Exit (South)', 'Dark Death Mountain (Top)'),
                       ('Hookshot Cave Exit (North)', 'Death Mountain Floating Island (Dark World)'),
                       ('Hookshot Cave Back Entrance', 'Hookshot Cave'),
                       ('Mimic Cave', 'Mimic Cave'),

                       ('Pyramid Hole', 'Pyramid'),
                       ('Pyramid Exit', 'Pyramid Ledge'),
                       ('Pyramid Entrance', 'Bottom of Pyramid')
                       ]

inverted_default_connections = [('Waterfall of Wishing', 'Waterfall of Wishing'),
                                ('Blinds Hideout', 'Blinds Hideout'),
                                ('Dam', 'Dam'),
                                ('Lumberjack House', 'Lumberjack House'),
                                ('Hyrule Castle Secret Entrance Drop', 'Hyrule Castle Secret Entrance'),
                                ('Hyrule Castle Secret Entrance Stairs', 'Hyrule Castle Secret Entrance'),
                                ('Hyrule Castle Secret Entrance Exit', 'Light World'),
                                ('Bonk Fairy (Light)', 'Bonk Fairy (Light)'),
                                ('Lake Hylia Fairy', 'Lake Hylia Healer Fairy'),
                                ('Lake Hylia Fortune Teller', 'Lake Hylia Fortune Teller'),
                                ('Light Hype Fairy', 'Swamp Healer Fairy'),
                                ('Desert Fairy', 'Desert Healer Fairy'),
                                ('Kings Grave', 'Kings Grave'),
                                ('Tavern North', 'Tavern'),
                                ('Chicken House', 'Chicken House'),
                                ('Aginahs Cave', 'Aginahs Cave'),
                                ('Sahasrahlas Hut', 'Sahasrahlas Hut'),
                                ('Cave Shop (Lake Hylia)', 'Cave Shop (Lake Hylia)'),
                                ('Capacity Upgrade', 'Capacity Upgrade'),
                                ('Kakariko Well Drop', 'Kakariko Well (top)'),
                                ('Kakariko Well Cave', 'Kakariko Well (bottom)'),
                                ('Kakariko Well Exit', 'Light World'),
                                ('Blacksmiths Hut', 'Blacksmiths Hut'),
                                ('Bat Cave Drop', 'Bat Cave (right)'),
                                ('Bat Cave Cave', 'Bat Cave (left)'),
                                ('Bat Cave Exit', 'Light World'),
                                ('Sick Kids House', 'Sick Kids House'),
                                ('Elder House (East)', 'Elder House'),
                                ('Elder House (West)', 'Elder House'),
                                ('Elder House Exit (East)', 'Light World'),
                                ('Elder House Exit (West)', 'Light World'),
                                ('North Fairy Cave Drop', 'North Fairy Cave'),
                                ('North Fairy Cave', 'North Fairy Cave'),
                                ('North Fairy Cave Exit', 'Light World'),
                                ('Lost Woods Gamble', 'Lost Woods Gamble'),
                                ('Fortune Teller (Light)', 'Fortune Teller (Light)'),
                                ('Snitch Lady (East)', 'Snitch Lady (East)'),
                                ('Snitch Lady (West)', 'Snitch Lady (West)'),
                                ('Bush Covered House', 'Bush Covered House'),
                                ('Tavern (Front)', 'Tavern (Front)'),
                                ('Light World Bomb Hut', 'Light World Bomb Hut'),
                                ('Kakariko Shop', 'Kakariko Shop'),
                                ('Lost Woods Hideout Drop', 'Lost Woods Hideout (top)'),
                                ('Lost Woods Hideout Stump', 'Lost Woods Hideout (bottom)'),
                                ('Lost Woods Hideout Exit', 'Light World'),
                                ('Lumberjack Tree Tree', 'Lumberjack Tree (top)'),
                                ('Lumberjack Tree Cave', 'Lumberjack Tree (bottom)'),
                                ('Lumberjack Tree Exit', 'Light World'),
                                ('Cave 45', 'Cave 45'),
                                ('Graveyard Cave', 'Graveyard Cave'),
                                ('Checkerboard Cave', 'Checkerboard Cave'),
                                ('Mini Moldorm Cave', 'Mini Moldorm Cave'),
                                ('Long Fairy Cave', 'Long Fairy Cave'),
                                ('Good Bee Cave', 'Good Bee Cave'),
                                ('20 Rupee Cave', '20 Rupee Cave'),
                                ('50 Rupee Cave', '50 Rupee Cave'),
                                ('Ice Rod Cave', 'Ice Rod Cave'),
                                ('Bonk Rock Cave', 'Bonk Rock Cave'),
                                ('Library', 'Library'),
                                ('Kakariko Gamble Game', 'Kakariko Gamble Game'),
                                ('Potion Shop', 'Potion Shop'),
                                ('Two Brothers House (East)', 'Two Brothers House'),
                                ('Two Brothers House (West)', 'Two Brothers House'),
                                ('Two Brothers House Exit (East)', 'Light World'),
                                ('Two Brothers House Exit (West)', 'Maze Race Ledge'),
                                ('Sanctuary', 'Sanctuary'),
                                ('Sanctuary Grave', 'Sewer Drop'),
                                ('Sanctuary Exit', 'Light World'),
                                ('Old Man House (Bottom)', 'Old Man House'),
                                ('Old Man House Exit (Bottom)', 'Death Mountain'),
                                ('Old Man House (Top)', 'Old Man House Back'),
                                ('Old Man House Exit (Top)', 'Death Mountain'),
                                ('Spectacle Rock Cave Peak', 'Spectacle Rock Cave (Peak)'),
                                ('Spectacle Rock Cave (Bottom)', 'Spectacle Rock Cave (Bottom)'),
                                ('Spectacle Rock Cave', 'Spectacle Rock Cave (Top)'),
                                ('Spectacle Rock Cave Exit', 'Death Mountain'),
                                ('Spectacle Rock Cave Exit (Top)', 'Death Mountain'),
                                ('Spectacle Rock Cave Exit (Peak)', 'Death Mountain'),
                                ('Paradox Cave (Bottom)', 'Paradox Cave Front'),
                                ('Paradox Cave (Middle)', 'Paradox Cave'),
                                ('Paradox Cave (Top)', 'Paradox Cave'),
                                ('Paradox Cave Exit (Bottom)', 'East Death Mountain (Bottom)'),
                                ('Paradox Cave Exit (Middle)', 'East Death Mountain (Bottom)'),
                                ('Paradox Cave Exit (Top)', 'East Death Mountain (Top)'),
                                ('Hookshot Fairy', 'Hookshot Fairy'),
                                ('Fairy Ascension Cave (Bottom)', 'Fairy Ascension Cave (Bottom)'),
                                ('Fairy Ascension Cave (Top)', 'Fairy Ascension Cave (Top)'),
                                ('Fairy Ascension Cave Exit (Bottom)', 'Fairy Ascension Plateau'),
                                ('Fairy Ascension Cave Exit (Top)', 'Fairy Ascension Ledge'),
                                ('Spiral Cave', 'Spiral Cave (Top)'),
                                ('Spiral Cave (Bottom)', 'Spiral Cave (Bottom)'),
                                ('Spiral Cave Exit', 'East Death Mountain (Bottom)'),
                                ('Spiral Cave Exit (Top)', 'Spiral Cave Ledge'),
                                ('Pyramid Fairy', 'Pyramid Fairy'),
                                ('East Dark World Hint', 'East Dark World Hint'),
                                ('Palace of Darkness Hint', 'Palace of Darkness Hint'),
                                ('Dark Lake Hylia Shop', 'Dark Lake Hylia Shop'),
                                ('Dark Lake Hylia Fairy', 'Dark Lake Hylia Healer Fairy'),
                                ('Dark Lake Hylia Ledge Fairy', 'Dark Lake Hylia Ledge Healer Fairy'),
                                ('Dark Lake Hylia Ledge Spike Cave', 'Dark Lake Hylia Ledge Spike Cave'),
                                ('Dark Lake Hylia Ledge Hint', 'Dark Lake Hylia Ledge Hint'),
                                ('Hype Cave', 'Hype Cave'),
                                ('Bonk Fairy (Dark)', 'Bonk Fairy (Dark)'),
                                ('Brewery', 'Brewery'),
                                ('C-Shaped House', 'C-Shaped House'),
                                ('Chest Game', 'Chest Game'),
                                ('Dark World Hammer Peg Cave', 'Dark World Hammer Peg Cave'),
                                ('Red Shield Shop', 'Red Shield Shop'),
                                ('Fortune Teller (Dark)', 'Fortune Teller (Dark)'),
                                ('Dark World Shop', 'Village of Outcasts Shop'),
                                ('Dark World Lumberjack Shop', 'Dark World Lumberjack Shop'),
                                ('Dark World Potion Shop', 'Dark World Potion Shop'),
                                ('Archery Game', 'Archery Game'),
                                ('Mire Shed', 'Mire Shed'),
                                ('Dark Desert Hint', 'Dark Desert Hint'),
                                ('Dark Desert Fairy', 'Dark Desert Healer Fairy'),
                                ('Spike Cave', 'Spike Cave'),
                                ('Hookshot Cave', 'Hookshot Cave'),
                                ('Superbunny Cave (Top)', 'Superbunny Cave (Top)'),
                                ('Cave Shop (Dark Death Mountain)', 'Cave Shop (Dark Death Mountain)'),
                                ('Superbunny Cave (Bottom)', 'Superbunny Cave (Bottom)'),
                                ('Superbunny Cave Exit (Bottom)', 'Dark Death Mountain (East Bottom)'),
                                ('Hookshot Cave Exit (North)', 'Death Mountain Floating Island (Dark World)'),
                                ('Hookshot Cave Back Entrance', 'Hookshot Cave'),
                                ('Mimic Cave', 'Mimic Cave'),
                                ('Inverted Pyramid Hole', 'Pyramid'),
                                ('Inverted Links House', 'Inverted Links House'),
                                ('Inverted Links House Exit', 'South Dark World'),
                                ('Inverted Big Bomb Shop', 'Inverted Big Bomb Shop'),
                                ('Inverted Dark Sanctuary', 'Inverted Dark Sanctuary'),
                                ('Inverted Dark Sanctuary Exit', 'West Dark World'),
                                ('Old Man Cave (West)', 'Bumper Cave'),
                                ('Old Man Cave (East)', 'Death Mountain Return Cave'),
                                ('Old Man Cave Exit (West)', 'West Dark World'),
                                ('Old Man Cave Exit (East)', 'Dark Death Mountain'),
                                ('Dark Death Mountain Fairy', 'Old Man Cave'),
                                ('Bumper Cave (Bottom)', 'Old Man Cave'),
                                ('Bumper Cave (Top)', 'Dark Death Mountain Healer Fairy'),
                                ('Bumper Cave Exit (Top)', 'Death Mountain Return Ledge'),
                                ('Bumper Cave Exit (Bottom)', 'Light World'),
                                ('Death Mountain Return Cave (West)', 'Bumper Cave'),
                                ('Death Mountain Return Cave (East)', 'Death Mountain Return Cave'),
                                ('Death Mountain Return Cave Exit (West)', 'Death Mountain'),
                                ('Death Mountain Return Cave Exit (East)', 'Death Mountain'),
                                ('Hookshot Cave Exit (South)', 'Dark Death Mountain'),
                                ('Superbunny Cave Exit (Top)', 'Dark Death Mountain'),
                                ('Pyramid Exit', 'Light World'),
                                ('Inverted Pyramid Entrance', 'Bottom of Pyramid')]

# non shuffled dungeons
default_dungeon_connections = [('Desert Palace Entrance (South)', 'Desert Palace Main (Inner)'),
                               ('Desert Palace Entrance (West)', 'Desert Palace Main (Outer)'),
                               ('Desert Palace Entrance (North)', 'Desert Palace North'),
                               ('Desert Palace Entrance (East)', 'Desert Palace Main (Outer)'),
                               ('Desert Palace Exit (South)', 'Desert Palace Stairs'),
                               ('Desert Palace Exit (West)', 'Desert Ledge'),
                               ('Desert Palace Exit (East)', 'Desert Palace Lone Stairs'),
                               ('Desert Palace Exit (North)', 'Desert Palace Entrance (North) Spot'),

                               ('Eastern Palace', 'Eastern Palace'),
                               ('Eastern Palace Exit', 'Light World'),
                               ('Tower of Hera', 'Tower of Hera (Bottom)'),
                               ('Tower of Hera Exit', 'Death Mountain (Top)'),

                               ('Hyrule Castle Entrance (South)', 'Hyrule Castle'),
                               ('Hyrule Castle Entrance (West)', 'Hyrule Castle'),
                               ('Hyrule Castle Entrance (East)', 'Hyrule Castle'),
                               ('Hyrule Castle Exit (South)', 'Hyrule Castle Courtyard'),
                               ('Hyrule Castle Exit (West)', 'Hyrule Castle Ledge'),
                               ('Hyrule Castle Exit (East)', 'Hyrule Castle Ledge'),
                               ('Agahnims Tower', 'Agahnims Tower'),
                               ('Agahnims Tower Exit', 'Hyrule Castle Ledge'),

                               ('Thieves Town', 'Thieves Town (Entrance)'),
                               ('Thieves Town Exit', 'West Dark World'),
                               ('Skull Woods First Section Hole (East)', 'Skull Woods First Section (Right)'),
                               ('Skull Woods First Section Hole (West)', 'Skull Woods First Section (Left)'),
                               ('Skull Woods First Section Hole (North)', 'Skull Woods First Section (Top)'),
                               ('Skull Woods First Section Door', 'Skull Woods First Section'),
                               ('Skull Woods First Section Exit', 'Skull Woods Forest'),
                               ('Skull Woods Second Section Hole', 'Skull Woods Second Section (Drop)'),
                               ('Skull Woods Second Section Door (East)', 'Skull Woods Second Section'),
                               ('Skull Woods Second Section Door (West)', 'Skull Woods Second Section'),
                               ('Skull Woods Second Section Exit (East)', 'Skull Woods Forest'),
                               ('Skull Woods Second Section Exit (West)', 'Skull Woods Forest (West)'),
                               ('Skull Woods Final Section', 'Skull Woods Final Section (Entrance)'),
                               ('Skull Woods Final Section Exit', 'Skull Woods Forest (West)'),
                               ('Ice Palace', 'Ice Palace (Entrance)'),
                               ('Ice Palace Exit', 'Dark Lake Hylia Central Island'),
                               ('Misery Mire', 'Misery Mire (Entrance)'),
                               ('Misery Mire Exit', 'Dark Desert'),
                               ('Palace of Darkness', 'Palace of Darkness (Entrance)'),
                               ('Palace of Darkness Exit', 'East Dark World'),
                               ('Swamp Palace', 'Swamp Palace (Entrance)'),
                               # requires additional patch for flooding moat if moved
                               ('Swamp Palace Exit', 'South Dark World'),

                               ('Turtle Rock', 'Turtle Rock (Entrance)'),
                               ('Turtle Rock Exit (Front)', 'Dark Death Mountain (Top)'),
                               ('Turtle Rock Ledge Exit (West)', 'Dark Death Mountain Ledge'),
                               ('Turtle Rock Ledge Exit (East)', 'Dark Death Mountain Ledge'),
                               ('Dark Death Mountain Ledge (West)', 'Turtle Rock (Second Section)'),
                               ('Dark Death Mountain Ledge (East)', 'Turtle Rock (Big Chest)'),
                               ('Turtle Rock Isolated Ledge Exit', 'Dark Death Mountain Isolated Ledge'),
                               ('Turtle Rock Isolated Ledge Entrance', 'Turtle Rock (Eye Bridge)'),

                               ('Ganons Tower', 'Ganons Tower (Entrance)'),
                               ('Ganons Tower Exit', 'Dark Death Mountain (Top)')
                               ]

inverted_default_dungeon_connections = [('Desert Palace Entrance (South)', 'Desert Palace Main (Inner)'),
                                        ('Desert Palace Entrance (West)', 'Desert Palace Main (Outer)'),
                                        ('Desert Palace Entrance (North)', 'Desert Palace North'),
                                        ('Desert Palace Entrance (East)', 'Desert Palace Main (Outer)'),
                                        ('Desert Palace Exit (South)', 'Desert Palace Stairs'),
                                        ('Desert Palace Exit (West)', 'Desert Ledge'),
                                        ('Desert Palace Exit (East)', 'Desert Palace Lone Stairs'),
                                        ('Desert Palace Exit (North)', 'Desert Palace Entrance (North) Spot'),
                                        ('Eastern Palace', 'Eastern Palace'),
                                        ('Eastern Palace Exit', 'Light World'),
                                        ('Tower of Hera', 'Tower of Hera (Bottom)'),
                                        ('Tower of Hera Exit', 'Death Mountain (Top)'),
                                        ('Hyrule Castle Entrance (South)', 'Hyrule Castle'),
                                        ('Hyrule Castle Entrance (West)', 'Hyrule Castle'),
                                        ('Hyrule Castle Entrance (East)', 'Hyrule Castle'),
                                        ('Hyrule Castle Exit (South)', 'Light World'),
                                        ('Hyrule Castle Exit (West)', 'Hyrule Castle Ledge'),
                                        ('Hyrule Castle Exit (East)', 'Hyrule Castle Ledge'),
                                        ('Thieves Town', 'Thieves Town (Entrance)'),
                                        ('Thieves Town Exit', 'West Dark World'),
                                        ('Skull Woods First Section Hole (East)', 'Skull Woods First Section (Right)'),
                                        ('Skull Woods First Section Hole (West)', 'Skull Woods First Section (Left)'),
                                        ('Skull Woods First Section Hole (North)', 'Skull Woods First Section (Top)'),
                                        ('Skull Woods First Section Door', 'Skull Woods First Section'),
                                        ('Skull Woods First Section Exit', 'Skull Woods Forest'),
                                        ('Skull Woods Second Section Hole', 'Skull Woods Second Section (Drop)'),
                                        ('Skull Woods Second Section Door (East)', 'Skull Woods Second Section'),
                                        ('Skull Woods Second Section Door (West)', 'Skull Woods Second Section'),
                                        ('Skull Woods Second Section Exit (East)', 'Skull Woods Forest'),
                                        ('Skull Woods Second Section Exit (West)', 'Skull Woods Forest (West)'),
                                        ('Skull Woods Final Section', 'Skull Woods Final Section (Entrance)'),
                                        ('Skull Woods Final Section Exit', 'Skull Woods Forest (West)'),
                                        ('Ice Palace', 'Ice Palace (Entrance)'),
                                        ('Misery Mire', 'Misery Mire (Entrance)'),
                                        ('Misery Mire Exit', 'Dark Desert'),
                                        ('Palace of Darkness', 'Palace of Darkness (Entrance)'),
                                        ('Palace of Darkness Exit', 'East Dark World'),
                                        ('Swamp Palace', 'Swamp Palace (Entrance)'),
                                        ('Swamp Palace Exit', 'South Dark World'),
                                        ('Turtle Rock', 'Turtle Rock (Entrance)'),
                                        ('Turtle Rock Ledge Exit (West)', 'Dark Death Mountain Ledge'),
                                        ('Turtle Rock Ledge Exit (East)', 'Dark Death Mountain Ledge'),
                                        ('Dark Death Mountain Ledge (West)', 'Turtle Rock (Second Section)'),
                                        ('Dark Death Mountain Ledge (East)', 'Turtle Rock (Big Chest)'),
                                        ('Turtle Rock Isolated Ledge Exit', 'Dark Death Mountain Isolated Ledge'),
                                        ('Turtle Rock Isolated Ledge Entrance', 'Turtle Rock (Eye Bridge)'),
                                        ('Inverted Ganons Tower', 'Inverted Ganons Tower (Entrance)'),
                                        ('Inverted Ganons Tower Exit', 'Hyrule Castle Ledge'),
                                        ('Inverted Agahnims Tower', 'Inverted Agahnims Tower'),
                                        ('Inverted Agahnims Tower Exit', 'Dark Death Mountain'),
                                        ('Turtle Rock Exit (Front)', 'Dark Death Mountain'),
                                        ('Ice Palace Exit', 'Dark Lake Hylia')]

# Regions that can be required to access entrances through rules, not paths
indirect_connections = {
    'Turtle Rock (Top)': 'Turtle Rock',
    'East Dark World': 'Pyramid Fairy',
    'Big Bomb Shop': 'Pyramid Fairy',
    'Dark Desert': 'Pyramid Fairy',
    'West Dark World': 'Pyramid Fairy',
    'South Dark World': 'Pyramid Fairy',
    'Light World': 'Pyramid Fairy',
    'Old Man Cave': 'Old Man S&Q'
}

